name: Deploy App

on:
  push:
    branches:
      - main


jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Add Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install app dependencies
        run: npm install

      - name: Build app
        run: npm run build:prod
      
      - name: Deploy app to github pages
        uses: MihaelaDanila100/ing-hubs-frontend-assignment@main
        with:
          ACCESS_TOKEN: ${{ secrets.G_TOKEN }}
          FOLDER: dist/browser

      